# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.24
    - name: Use Node.js 16.13
      uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
      with:
        node-version: 16.13
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
    - run: pnpm test:unit
